apiVersion: 1

datasources:
  - name: InfluxDB-v2-Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: your-org
      defaultBucket: market_data
      tlsSkipVerify: true
    secureJsonData:
      token: dev-token-please-change
